Ultra-Punks/bramble

server/db/models/community.js
server/db/models/communityMod.js
server/db/models/communitySubs.js
server/db/models/index.js
server/db/models/location.js
server/db/models/locationReview.js
server/db/models/photos.js
server/db/models/postComment.js
server/db/models/user.js
server/db/models/userFollowers.js
server/db/models/userPost.js

F 01 models

---

server/db/models/index.js
server/db/models/location.js
server/index.js

debugged associations with group

---

README.md
client/components/index.js
client/components/single-post-view.js
client/routes.js
package-lock.json
package.json
server/api/bramble-vision.json
server/api/google-vision.js
server/api/index.js
server/db/models/postComment.js

initial image detection section

---

package-lock.json
package.json
script/seed.js
server/db/models/community.js
server/db/models/index.js
server/db/models/location.js
server/db/models/user.js

F 06 seed file

---

server/api/google-vision.js

added logo and text detection

---

package-lock.json

debugged package json

---

public/style.css
script/seed.js
server/db/models/index.js
server/db/models/user.js
server/index.js

Group Reviewed Seed updates / debugging completed

F 17 seed update

---

client/components/PostFeed.js
client/components/ProfileView.js
client/store/index.js
client/store/singlePost.js
client/store/userFeed.js
public/style.css
server/api/index.js
server/api/posts.js
server/api/users.js

F 19 posts

---

client/components/communityProfile.js
client/components/communitySearch.js
client/routes.js
client/store/community.js
server/api/community.js

F 18 community post

---

client/components/navbar.js

Added Map connectivity to navbar

---

client/components/Map.js
client/components/ProfileView.js
public/style.css

added map to profile view

---

client/components/Map.js
client/components/navbar.js
client/store/user.js

minor tweaks to signup history push, map marker

---

client/components/Map.js
client/store/locations.js

removed console logs

---

client/components/FeedPostPreview.js
client/components/PostPreview.js
client/components/ProfileView.js
client/components/ShowFollowing.js
client/routes.js
client/store/user.js
client/store/userFeed.js
package-lock.json
package.json
public/style.css
server/api/posts.js

user feed now displays in order with timestamp

---

client/components/ProfileView.js
client/components/communityProfile.js
client/routes.js
client/store/user.js
client/store/userFeed.js
server/api/users.js
server/imageRec.js

debugged community view error & restructured reducer for profiles

---

client/components/DisplayFollowUnfollow.js
client/components/DisplaySubUnsub.js
client/components/ProfileView.js
client/components/ShowMembers.js
client/components/communityProfile.js
client/components/communitySearch.js
client/components/index.js
client/store/allCommunities.js
client/store/community.js
client/store/index.js
client/store/isFollowing.js
client/store/singleProfile.js
script/seed.js
server/api/community.js
server/api/posts.js
server/api/users.js
server/auth/index.js
server/db/models/communityMod.js
server/db/models/communitySubs.js
server/db/models/index.js

subscribe to communities feature refactored community store

---

client/components/CommunityFeed.js
client/components/CommunityPostComment.js
client/components/CommunityPostPreview.js
server/api/posts.js

added communityFeed

---

client/components/LandingPage.js
client/store/allCommunities.js
server/api/community.js

debugged landing page & random communities display

---

client/components/CommunityPostComment.js
client/components/CommunityPostPreview.js
client/components/SingleComment.js
client/components/communityProfile.js
client/store/singleComment.js
client/store/singlePost.js
server/api/comments.js
server/api/posts.js

Post comment updates

---

client/components/AddLocation.js
client/components/AddLocationForm.js
client/components/Map.js
client/components/ProfileView.js
client/components/ShowSubscriptions.js
client/components/SingleLocation.js
client/components/add-post-form.js
client/components/add-post.js
client/components/index.js
client/routes.js
client/store/locations.js
client/store/singleLocation.js
client/store/singleProfile.js
public/style.css
server/api/locations.js
server/api/posts.js
server/api/users.js
server/auth/index.js

Bootstrap map

---

client/components/EditProfile.js
client/components/EditProfileForm.js
client/components/index.js
client/components/single-post-view.js
public/style.css

css for single post view

---

client/components/index.js
client/routes.js
client/store/singlePost.js
public/index.html
public/style.css

debugged missing component routes

---

client/components/AddCommentForm.js
client/components/PostPreview.js
client/store/postComments.js
server/api/comments.js

Addcomment page

---

client/components/AddCommentFormCom.js
client/components/CommunityPostPreview.js
public/style.css

debugged comment form and other stuff

---

client/components/LandingPage.js
client/components/SingleComment.js
client/components/navbar.js
public/style.css

Single comment update

---

client/components/CommunityPostComment.js
client/components/PostComment.js
client/components/SingleComment.js
package-lock.json
package.json

Comment update

---

client/components/AddCommentFormFeed.js
client/components/CommunityFeed.js
client/components/CommunityPostComment.js
client/components/CommunityPostPreview.js
client/components/FeedPostComment.js
client/components/FeedPostPreview.js
client/components/FollowingFeed.js
client/components/PostComment.js
client/components/PostPreview.js
client/components/communityProfile.js
client/components/user-home.js
client/store/generalUserFeed.js
client/store/postComments.js
client/store/userFeed.js
server/api/photos.js
server/api/posts.js

delete button works for posts as well as comments

---

script/seed.js
server/db/models/location.js

Updated Location model and location seed data.

Location seed updates

---

client/components/communitySearch.js
script/seed.js
server/api/middleware.js

communityseed

---

client/components/CommunityPostComment.js
client/components/CommunityPostPreview.js
client/components/FeedPostComment.js
client/components/FeedPostPreview.js
client/components/PostComment.js
client/components/PostPreview.js
client/store/generalUserFeed.js
client/store/userFeed.js
package-lock.json
package.json
public/style.css
server/api/comments.js
server/api/posts.js

Like button

---

client/components/communitySearch.js
script/seed.js

reseed community data

---

client/components/Map.js
client/components/MapForProfile.js
client/components/RedPin.js
public/style.css

styling for map popups

---

client/components/AddLocationForm.js
client/components/AddLocationReview.js
client/components/LocationReviews.js
client/components/Map.js
client/components/SingleLocation.js
client/store/locations.js
client/store/singleLocation.js
public/locationStyle.css
public/style.css
server/api/locationReviews.js
server/db/models/location.js

refactored add location review backend to stop refresh on submit

---

script/seed.js

Added location in seed for cooking community that was recently added.

added culinary institute to seed file

---

.gitignore
client/components/Map.js
server/imageRec.js

526debugging
